title: Josh Bryan's Random Thoughts
description: > # this means to ignore newlines until "baseurl:"
  My random thoughts.
email: josh.bryan@gmail.com
twitter_username: jbryanchi
github_username:  jbryan
linkedin_username:  joshuaabryan
permalink: /blog/:year/:month/:day/:title/
paginate: 5

highlighter: rouge
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
